# Generated by Django 5.2.5 on 2025-09-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
