# Generated by Django 5.2.5 on 2025-09-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productvariant_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-priority', 'name']},
        ),
        migrations.AddField(
            model_name='discount',
            name='priority',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('BRAND', 'Brand'), ('CATEGORY', 'Category')], default='PRODUCT', help_text='Priority when multiple discounts apply', max_length=20),
        ),
        migrations.AlterField(
            model_name='discount',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='List of categories (use Category enum values)'),
        ),
    ]
