# Generated by Django 5.2.5 on 2025-09-10 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_discount_options_discount_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
