# Generated by Django 5.2.5 on 2025-09-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_discount_end_date_alter_discount_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
