# Generated by Django 5.2.5 on 2025-09-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariant_price_adjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price_adjustment',
        ),
    ]
